spring:
  profiles.active: dev

server:
  servlet:
    context-path: /visa

visa:
  rootUri: https://sandbox.api.visa.com
  keystore:
    file: keystore.jks
    password:
  project:
    userId:
    password:
